spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: 1210
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: liquibase/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
