
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    liquibase:
      drop-first: true

  mvc:
    hiddenmethod:
      filter:
        enabled=true:
logging:
  file:
    name: ${LOGGING_FILE_NAME:logs/application:log}
    path: ${LOGGING_FILE_PATH:logs}
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 10


